// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for UserProfileAccountRole.
const (
	Admin    UserProfileAccountRole = "admin"
	Employee UserProfileAccountRole = "employee"
	Manager  UserProfileAccountRole = "manager"
)

// AuthTokenResponse defines model for AuthTokenResponse.
type AuthTokenResponse struct {
	// AccessToken JWT ~15min expiry
	AccessToken string `json:"accessToken"`

	// RefreshToken random string with long expiry time
	RefreshToken string      `json:"refreshToken"`
	User         UserProfile `json:"user"`
}

// Error defines model for Error.
type Error struct {
	Code    interface{}             `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message interface{}             `json:"message"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// ScheduleResponse defines model for ScheduleResponse.
type ScheduleResponse struct {
	Message string `json:"message"`
	Week    string `json:"week"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	Email     openapi_types.Email `json:"email"`
	FirstName interface{}         `json:"firstName,omitempty"`
	LastName  interface{}         `json:"lastName,omitempty"`
	Password  string              `json:"password"`
	Phone     interface{}         `json:"phone,omitempty"`
}

// UserProfile defines model for UserProfile.
type UserProfile struct {
	AccountRole UserProfileAccountRole `json:"accountRole"`
	Email       interface{}            `json:"email"`
	FirstName   *string                `json:"firstName"`
	Id          openapi_types.UUID     `json:"id"`
	LastName    *string                `json:"lastName"`
	Phone       *string                `json:"phone"`
}

// UserProfileAccountRole defines model for UserProfile.AccountRole.
type UserProfileAccountRole string

// GetScheduleParams defines parameters for GetSchedule.
type GetScheduleParams struct {
	Week openapi_types.Date `form:"week" json:"week"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody = SignupRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// login the user and get tokens
	// (POST /auth/login)
	Login(c *gin.Context)
	// create an account for the user
	// (POST /auth/signup)
	Signup(c *gin.Context)

	// (GET /schedule)
	GetSchedule(c *gin.Context, params GetScheduleParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Signup operation middleware
func (siw *ServerInterfaceWrapper) Signup(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Signup(c)
}

// GetSchedule operation middleware
func (siw *ServerInterfaceWrapper) GetSchedule(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetScheduleParams

	// ------------- Required query parameter "week" -------------

	if paramValue := c.Query("week"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument week is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "week", c.Request.URL.Query(), &params.Week)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter week: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetSchedule(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/signup", wrapper.Signup)
	router.GET(options.BaseURL+"/schedule", wrapper.GetSchedule)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse AuthTokenResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Login401JSONResponse Error

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SignupRequestObject struct {
	Body *SignupJSONRequestBody
}

type SignupResponseObject interface {
	VisitSignupResponse(w http.ResponseWriter) error
}

type Signup201JSONResponse UserProfile

func (response Signup201JSONResponse) VisitSignupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type Signup400JSONResponse Error

func (response Signup400JSONResponse) VisitSignupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Signup409JSONResponse Error

func (response Signup409JSONResponse) VisitSignupResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type GetScheduleRequestObject struct {
	Params GetScheduleParams
}

type GetScheduleResponseObject interface {
	VisitGetScheduleResponse(w http.ResponseWriter) error
}

type GetSchedule200JSONResponse ScheduleResponse

func (response GetSchedule200JSONResponse) VisitGetScheduleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// login the user and get tokens
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// create an account for the user
	// (POST /auth/signup)
	Signup(ctx context.Context, request SignupRequestObject) (SignupResponseObject, error)

	// (GET /schedule)
	GetSchedule(ctx context.Context, request GetScheduleRequestObject) (GetScheduleResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *gin.Context) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Signup operation middleware
func (sh *strictHandler) Signup(ctx *gin.Context) {
	var request SignupRequestObject

	var body SignupJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Signup(ctx, request.(SignupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Signup")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SignupResponseObject); ok {
		if err := validResponse.VisitSignupResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetSchedule operation middleware
func (sh *strictHandler) GetSchedule(ctx *gin.Context, params GetScheduleParams) {
	var request GetScheduleRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSchedule(ctx, request.(GetScheduleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSchedule")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetScheduleResponseObject); ok {
		if err := validResponse.VisitGetScheduleResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xWTW/cNhD9K+y0R8G7blqg1S0pgsJFUBh2ih6SoKDFkcSEX+aQthfG9rcXJLUf0mpt",
	"H7y97VLDmTfvDR/5CI3Vzho0gaB+BGp61Dz/fBtD/9F+Q3OF5KwhTIvOW4c+SMwhvGmQKAelvwKp8dIF",
	"aQ3U8MffH9m/5z9raRg+OOlXUEFYOYQaKHhpOlhX4LH1SP2RFJ4bYTUr4exehp4pa7ohHwtS41zSSOhT",
	"sh88tlDD94tdj4uhwcVfhP7S21YqhHUGchulRwH1p1FbE4hD8i/bqvbmKzYhVX3vvfWHHDVWZObwgWun",
	"sP4M0txxJcU/0rgYPgPUJipVEtZDE3lpXYHAwKUqXAshEy1cXe7lDz7iDBaNRLzLdQ/TTrrNAHdb5lr7",
	"YDtprvA2IoXjWFquCKtJ+6i5VOlHa73mAephZUY2x4nurRcpWkvzAU0Xeqh/OQidNLBJuN0/18J106OI",
	"Co8P84SzEbR7xG8zHyZActTTTF7LzkR3cipb6Sn8yfWRCahA8ae/v1iLClxvzcsm7UVC7R/MOcOx0YQr",
	"Wz6iiTofWKFlOpuaG96hhwpQO2VXuC/CDvHTRE6pGHGZ1vhNqj46ebvcUowSxyjFnED7/D+bc8vwM5ET",
	"unPlTWf7zB3SnrZK09osowypArzzeM82x8azt5cXUMEdeirevDw7P1smdNah4U5CDW/Olmdvsr6hz3It",
	"eAz9QiX3yFraMvNJUZ6G/kJAXcwFCnSk8M6KVfFNE9CUM+Kckk3esfhK1uwuqudcfmRc6zFBicK8UAwh",
	"A/5xuXy12of3ZwYwvuGuY75r2qjUiinbdSiYNIwbwULaS0wSRRSJ6J+W568GrlxWM4AuyuXEfvMo0ATJ",
	"FeXBoqg19yuoIcvJQo8sXYUZaodhgJtji+yUre647sUKTyT82GdfpPzrkTt+WxxQnD6zxiMPKBjtDcB3",
	"ReXl/6fyRXqCUCn76+nLvk9mxLjyyMWK4YOkMJ2uwgvjhg2OxVrrt9NWxosGU0o4OpwZrd8xbIwr25Hn",
	"GgN6gvrTIyQvgtuI+UFqsgdvbu7xiFR77W4NXfAw8+ZcfzmhkRw8XWaY3VDCKMSbFLBer/8LAAD//7zU",
	"OB7cCwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
